import "./polyfills";
import fs from "node:fs";
import type { Dirent } from "node:fs";
import type { ParsedPath } from "node:path";
import * as path from "node:path";
import react from "react";
import type { Component } from "react";
import type { Store } from "redux";
import type { Story } from "@storybook/react";
import { storiesOf } from "@storybook/react";
import type { AppRouter } from "@/App";
import App from "@/App";
import type { Page } from "./page";
import page from "./page";
import type { Css } from "./styles";
import styles from "./styles";
import config from "/config";
import type { Config } from "/config";
