name: Test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22, 24]

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "${{ matrix.node-version }}"

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v5
        with:
          path: node_modules
          key: node_modules-${{ matrix.node-version }}-${{ hashFiles('package.json', 'package-lock.json') }}

      - if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci --no-audit

      - run: npx vitest
